PATH=$PATH:.

alias la="ls -la"
alias lt="ls -lt"
alias m="make"
alias mi="make install"
alias mc="make clean"
alias d="dirs"
alias pd="pushd"
alias p2="pushd +2"
alias p3="pushd +3"
alias p4="pushd +4"
alias h="history"
alias x="exit"
alias ntp="systemctl reload-or-restart ntpdate"
