#!/bin/sh

VER=5370.v3.0
DEV=5370
CAPE=cape-bone-${DEV}-00A0
SLOTS=`ls /sys/devices/bone_capemgr.*/slots`

if test ! -f .profile; then
        cp $VER/unix_env/.profile .;
fi

# out-of-the-box BBB doesn't seem to have NTP configured
if grep -q 'NTPSERVERS=""' /etc/default/ntpdate ; then
	cp $VER/unix_env/ntpdate /etc/default;
fi

if date | grep -q 2000; then (echo start NTP; systemctl reload-or-restart ntpdate); fi

# setup device tree before running interpreter
if test ! -f /lib/firmware/${CAPE}.dts; then
	echo create ${DEV} device tree;
	cp $VER/unix_env/${CAPE}.dts /lib/firmware;
	(cd /lib/firmware; dtc -O dtb -o ${CAPE}.dtbo -b 0 -@ ${CAPE}.dts);
fi

if ! grep -q ${DEV} $SLOTS ; then
	echo load ${DEV} device tree;
	echo cape-bone-${DEV} > $SLOTS;
fi

if [ $DEV != "test" ] ; then
	$VER/h;
fi
