update=Thu 28 Jul 2011 09:25:02 AM MDT
last_client=cvpcb
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=5370
LibDir=../modules
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
